version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword
  web:
    build: .
    container_name: web
    command: python -m flask run --host=0.0.0.0
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  db_data:
