version: "3.8"
services:
  db:
    build: ./db
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: BBqfxDg1hQ+AaRbT12knLBFoLuvGwbZ+sGmCCk0FDGvO
    ports:
      - 5432:5432

  web:
    build: .
    container_name: web
    command: ./start_server.sh
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db_data:
